services:
  db:
    container_name: db
    build: 
      context: db
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${PASSWORD_PG}
    networks:
      - compose-net
  db_repl:
    container_name: db_repl
    build: 
      context: db_repl
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${PASSWORD_PG}
    networks:
      - compose-net
    depends_on:
      - db
  bot:
    container_name: bot
    build:
      context: bot
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - compose-net
    env_file:
      - .env
networks:
  compose-net:
    driver: bridge