- hosts: all
  tasks:
    - name: Install PostgreSQL, Python, Git
      become: yes
      apt:
        name: 
          - postgresql
          - python
          - git
        state: latest
        update_cache: true
      
    - name: Clone project from GitHub
      git:
        repo: https://github.com/larinskiy/pt-start-bot.git
        dest: /tmp/pt-start-bot
        force: yes

    - name: Copy .env 
      copy:
        src: .env
        dest: /tmp/pt-start-bot/
        mode: 0744

    - name: Allow execute init for postgres
      file:
        path: /tmp/pt-start-bot/db/db_master_init.sh
        state: file
        mode: 0755

    - name: Rename and move db_master_init.sql
      become: yes
      copy: remote_src=True src=/tmp/pt-start-bot/db/db_master_init.sql dest=/init.sql

    - name: Allow read init.sql for postgres
      become: yes
      file:
        path: /tmp/pt-start-bot/db/db_master_init.sql
        state: file
        mode: 0744

    - name: Export environment file for postgres and init
      become: yes
      become_user: postgres
      shell: export $(cat /tmp/pt-start-bot/.env | xargs) && /tmp/pt-start-bot/db/db_master_init.sh

    - name: Export environment file for bot
      shell: export $(cat /tmp/pt-start-bot/.env | xargs)
    
    - name: Install requirements with pip
      command: pip install -r /tmp/pt-start-bot/requirements.txt

    - name: Run bot.py
      command: python /tmp/pt-start-bot/bot.py