- hosts: all
  tasks:
    - name: Install PostgreSQL, Python, Git
      become: yes
      apt:
        name: postgresql
        name: python
        name: git
        state: present
      
    - name: Clone project from GitHub
      git:
        repo: https://github.com/larinskiy/pt-start-bot.git
        dest: /tmp/pt-start-bot
        force: yes

    - name: Copy .env 
      copy:
        src: .env
        dest: /tmp/pt-start-bot/
        mode: 0744

    - name: Export environment file for bot
      command: /bin/bash -c "export $(cat /tmp/pt-start-bot/.env | xargs)"

    - name: Export environment file for postgres
      become: yes
      become_user: postgres
      command: /bin/bash -c "export $(cat /tmp/pt-start-bot/.env | xargs)"

    - name: Allow execute init for postgres
      file:
        path: /tmp/pt-start-bot/db/db_master_init.sh
        state: file
        mode: 0755

    - name: Postgresql initialize
      become: yes
      become_user: postgres
      command: /tmp/pt-start-bot/db/db_master_init.sh
      args:
        chdir: /tmp/pt-start-bot/db
    
    - name: Restart PostgreSQL
      become: yes
      service:
        name: postgresql
        state: restarted

    - name: Install requirements with pip
      command: pip install -r /tmp/pt-start-bot/requirements.txt

    - name: Run bot.py
      command: python /tmp/pt-start-bot/bot.py
