CREATE TABLE IF NOT EXISTS Phones (
    PhoneID SERIAL PRIMARY KEY,
    Phone VARCHAR(64) NOT NULL
);

INSERT INTO Phones (PhoneID, Phone) VALUES
(DEFAULT, '88005555555'),
(DEFAULT, '84990519301');

CREATE TABLE IF NOT EXISTS Emails (
    EmailID SERIAL PRIMARY KEY,
    Email VARCHAR(64) NOT NULL
);

INSERT INTO Emails (EmailID, Email) VALUES
(DEFAULT, 'first@email.com'),
(DEFAULT, 'second@email.com');

